application:
  datasource:
    url: jdbc:postgresql://ep-autumn-wave-a8qdk74l-pooler.eastus2.azure.neon.tech/Fit-Ai?user=Fit-Ai_owner&password=npg_uS58QMazsUBJ&sslmode=require
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    logging:
      level:
        org.hibernate.SQL: debug
        org.hibernate.type.descriptor.sql.BasicBinder: trace


