spring:
  application:
      name: Graduation_Project
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 10
  datasource:
    url: ${application.datasource.url}
    username: ${application.datasource.username}
    password: ${application.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
application:
  security:
    access-token:
      secret-key: T1Wg3DaZ+wG5l+gdJgsmGx0P6MBSwl6Dk6jUzqKwyr8=
