spring:
  application:
    name: Graduation_Project
  profiles:
    active: '@spring.profiles.active@'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 10
  datasource:
    url: ${application.datasource.url}
    username: ${application.datasource.username}
    password: ${application.datasource.password}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 643522420506-5ddq0ul48gqhfvkv4ki7lhhj2oksssdi.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

application:
  security:
    access-token:
      secret-key: T1Wg3DaZ+wG5l+gdJgsmGx0P6MBSwl6Dk6jUzqKwyr8=

cloudinary:
  cloud-name: dt6tkjbv0
  api-key: 847815547535319
  api-secret: lXtK-kVtnNDjf45r4210rbwRS-k
