spring:
  application:
    name: Graduation_Project
  profiles:
    active: '@spring.profiles.active@'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 10
        query.plan_cache_max_size: 0
  datasource:
    url: ${application.datasource.url}
    username: ${application.datasource.username}
    password: ${application.datasource.password}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

application:
  security:
    access-token:
      secret-key: T1Wg3DaZ+wG5l+gdJgsmGx0P6MBSwl6Dk6jUzqKwyr8=

cloudinary:
  cloud-name: dt6tkjbv0
  api-key: 847815547535319
  api-secret: lXtK-kVtnNDjf45r4210rbwRS-k
